on: push
name: Laravel CI
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.2
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan migrate
        php artisan api:GetBlockInfo
        php artisan api:GetEraRewards
        php artisan api:GetAccountBalance
        php artisan api:GetValidators
        php artisan api:GetAccountInfo
        php artisan api:GetPeers
 
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
